FROM golang:1.21-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /bin/service ./cmd/load-generator

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/service /bin/service
CMD ["/bin/service"]
