FROM golang:1.21-bookworm AS builder
RUN apt-get update && apt-get install -y --no-install-recommends gcc libc6-dev librdkafka-dev pkg-config && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 go build -ldflags="-s -w" -o /bin/service ./cmd/worker
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates librdkafka1 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /bin/service /bin/service
CMD ["/bin/service"]
